name: "FastAPI"

services:

  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - database

#  api:
#    build: .
#    restart: unless-stopped
#    ports:
#      - "8000:8000"
#    expose:
#      - 8000
#    depends_on:
#      - database